version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitSyncTestProject
  gitServerName: lara
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: Lakshitha-Ramesh-IBM
  gitBranch: main
